version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
build_script:
- ps: >-
    dotnet clean

    dotnet restore

    dotnet build
test_script:
- ps: dotnet test
artifacts:
- path: .\src\CalciCi\bin\Release\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: m7+aV1s4BVZh50hw26xIWUACRqjX79zoXba8XVnW0hFqb+XQrLti48ewcWB6k62x
  skip_symbols: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
