version: 1.0.{build}
build_script:
- ps: .\build.ps1
artifacts:
- path: '**/*.nupkg'
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: oy2iqonor2vce3ivvieazjxwtdd4mnnull3x2txo6ufj5e
  artifact: /.*\.nupkg/